name = "lp-xoamaan-6c-llwin"
compatibility_date = "2024-01-01"
pages_build_output_dir = "."

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "XOAMA_KV"
id = "ae45bcd2386d4fd9a98473173784607b"
